Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2023-12, with the labels that each got.

#86 Switch to goflag
  CODE_OF_CONDUCT.md
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  go.work.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/load.go
  internal/config/secret.go
  internal/config/secret_test.go
  internal/config/slice.go
  internal/config/slice_test.go
  internal/config/types.go
  internal/http/main.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/openvpn/client.go
  internal/openvpn/handler.go
  internal/openvpn/main_test.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  pkg/plugin/main.go
  pkg/plugin/plugin.go
  renovate.json
Labels: enhancement

#88 Use minimal token interface to ignore non compliant token claims
  internal/oauth2/handler.go
  internal/oauth2/idtoken/main.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/providers/github/user.go
  internal/oauth2/types.go
Labels: bug

#89 OIDC: Use html template on unauthorized errors
  .golangci.yaml
  Makefile
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  go.work.sum
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/log/logger.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/types.go
  internal/openvpn/callbacks.go
  internal/utils/http.go
  internal/utils/http_test.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  pkg/plugin/plugin.go
Labels: enhancement

#85 Adding Google Workspace / Google Cloud as working provider
  docs/Providers.md
Labels: docs

#93 Implement token store
  cmd/root.go
  internal/config/config.go
  internal/config/defaults.go
  internal/config/types.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/types.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/types.go
  internal/storage/errors.go
  internal/storage/storage.go
  pkg/plugin/plugin.go
Labels: enhancement

#92 Add default template for more user-friendly HTML messages
  internal/config/defaults.go
  internal/oauth2/callback.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/openvpn/main_test.go
  internal/ui/files.go
  internal/ui/index.gohtml
  internal/ui/static/mvp.css
  pkg/testutils/main.go
Labels: enhancement

#96 Optimize connection parser
  internal/openvpn/connection/bench_test.go
  internal/openvpn/connection/client.go
Labels: enhancement

#97 Add benchmark for OpenVPN Handler
  .github/workflows/ci.yaml
  internal/openvpn/bench_test.go
  internal/openvpn/connection/bench_test.go
  pkg/testutils/main.go
Labels: enhancement

#94 Add non-interactive session refresh via token
  .github/workflows/ci.yaml
  .gitignore
  .golangci.yaml
  README.md
  cmd/root.go
  cmd/root_test.go
  docs/Configuration.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/types.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/main.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/providers/github/user.go
  internal/oauth2/refresh.go
  internal/oauth2/refresh_test.go
  internal/oauth2/types.go
  internal/oauth2/types/userdata.go
  internal/openvpn/bench_test.go
  internal/openvpn/callbacks.go
  internal/openvpn/client.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/types.go
  internal/state/state_test.go
  internal/storage/storage.go
  internal/storage/storage_test.go
  pkg/plugin/callbacks.go
  pkg/plugin/plugin.go
  pkg/testutils/listener.go
  pkg/testutils/main.go
  tests/docker-compose.yaml
Labels: enhancement

#98 Avoid unnecessary memory allocations in OpenVPN handler
  internal/openvpn/client.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/state/bench_test.go
  internal/state/state.go
  internal/state/state_test.go
  internal/ui/index.gohtml
  internal/ui/static/favicon.png
Labels: enhancement

#99 Implement oauth2 PKCE and nonce validation
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/Configuration.md
  docs/Installation.md
  docs/Providers.md
  docs/_Footer.md
  go.mod
  go.sum
  go.work.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/decode_hooks_test.go
  internal/config/defaults.go
  internal/config/types.go
  internal/config/types_test.go
  internal/oauth2/handler.go
  internal/oauth2/provider.go
  internal/oauth2/refresh.go
  internal/oauth2/types.go
  internal/openvpn/client.go
  internal/ui/index.gohtml
  renovate.json
Labels: enhancement

#101 Support session refresh for Github Provider
  Makefile
  cmd/root_test.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/refresh.go
  internal/oauth2/providers/github/refresh.go
  internal/oauth2/refresh.go
  internal/oauth2/refresh_test.go
  internal/oauth2/types.go
  internal/openvpn/client.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  pkg/testutils/main.go
Labels: enhancement
