Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2023-10, with the labels that each got.

#38 general: Refactor code, enable more linters
  .editorconfig
  .golangci.yaml
  cmd/root.go
  cmd/root_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/decode_hooks.go
  internal/config/errors.go
  internal/config/types.go
  internal/oauth2/callback.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/providers/generic/endpoints.go
  internal/oauth2/providers/generic/errors.go
  internal/oauth2/providers/generic/main.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/providers/github/api.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/providers/github/endpoints.go
  internal/oauth2/providers/github/main.go
  internal/oauth2/providers/github/user.go
  internal/oauth2/types.go
  internal/openvpn/client.go
  internal/openvpn/client_connection.go
  internal/openvpn/client_connection_test.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/connection/errors.go
  internal/openvpn/errors.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/types.go
  internal/state/errors.go
  internal/state/state.go
  internal/state/state_test.go
  internal/utils/slices.go
  internal/utils/slices_test.go
  internal/utils/strings.go
  internal/utils/strings_test.go
  internal/utils/url.go
  internal/utils/url_test.go
  main.go
Labels: chore

#39 Add graceful shutdown to http listener
  cmd/root.go
  cmd/root_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/openvpn/main.go
Labels: enhancement

#40 feat: Prepare OpenVPN server plugin
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/load.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/openvpn/callbacks.go
  internal/openvpn/client.go
  internal/openvpn/main_test.go
  internal/state/state.go
  internal/state/state_test.go
Labels: enhancement

#41 OpenVPN Plugin
  .github/workflows/ci.yaml
  .goreleaser.yaml
  cmd/root.go
  go.work
  go.work.sum
  internal/http/main.go
  internal/oauth2/handler.go
  internal/openvpn/client.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/main.go
  internal/state/state.go
  plugin/.gitignore
  plugin/Dockerfile
  plugin/Makefile
  plugin/callbacks.go
  plugin/client.go
  plugin/go.mod
  plugin/go.sum
  plugin/logger.go
  plugin/main.go
  plugin/plugin.go
  plugin/plugin_wrapper.go
  tests/docker-compose.yaml
Labels: enhancement

#42 Add arm64 plugin builds
  .github/workflows/ci.yaml
  .goreleaser.yaml
  plugin/Dockerfile
Labels: enhancement

#43 CI: test release in CI
  .github/workflows/ci.yaml
  .goreleaser.yaml
  internal/openvpn/client.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  packaging/config.yaml
  packaging/preremove.sh
Labels: chore

#45 Manual configuration of token url
  internal/http/main.go
  internal/oauth2/providers/github/endpoints.go
Labels: bug

#51 update dependencies
  .goreleaser.yaml
  cmd/root_test.go
  go.mod
  go.sum
  go.work
  internal/config/config_test.go
  internal/config/decode_hooks_test.go
  internal/http/main_test.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/check_test.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/main_test.go
  internal/state/state_test.go
  internal/utils/slices_test.go
  pkg/testutils/go.mod
  pkg/testutils/go.sum
  pkg/testutils/main.go
Labels: chore

#52 Fixed go panic with GitHub provider
  internal/oauth2/handler.go
  internal/oauth2/providers/github/endpoints.go
Labels: bug

#55 Fix --html.template option
  internal/config/config.go
  internal/config/decode_hooks.go
  internal/config/decode_hooks_test.go
  internal/config/types.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
Labels: bug

#56 fix goreleaser tag
  .github/workflows/ci.yaml
Labels: chore

#58 Add default scopes based on provider
  docs/Providers.md
  internal/config/config.go
  internal/config/defaults.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/main.go
  internal/oauth2/providers/github/main.go
  internal/oauth2/types.go
  pkg/plugin/callbacks.go
  pkg/plugin/client.go
  pkg/plugin/logger.go
  pkg/plugin/main.go
  pkg/plugin/plugin.go
  tests/docker-compose.yaml
Labels: enhancement

#57 Changed docs
  docs/Configuration.md
  docs/Home.md
  docs/Installation.md
  docs/Providers.md
Labels: docs
