Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-10, with the labels that each got.

#328 chore(deps): bump dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#329 fix mime types access
  packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
Labels: 🐞 bug

#333 log warning if session id exists but not used.
  go.mod
  go.sum
  go.work.sum
  internal/openvpn/client.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🐞 bug

#332 Add some certbot instructions in wiki
  docs/HTTPS Listener.md
Labels: 📖 docs
