Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-05, with the labels that each got.

#258 Update nl.json
  internal/ui/assets/i18n/nl.json
Labels: ✨ enhancement

#261 Add masq
  docs/demo/docker-compose.yaml
  docs/demo/openvpn-server.conf
  internal/ui/assets/i18n/ua.json
Labels: ✨ enhancement

#264 update dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: 🛠️ dependencies

#266 Update question.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/question.yaml
Labels: chore

#267 fix: better error message against older OpenVPN versions
  internal/openvpn/handler.go
Labels: 🐞 bug

#269 fix: better error message if oauth2 provider with manual endpoints is used
  docs/Configuration.md
  docs/FAQ.md
  internal/config/flags.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/user.go
Labels: 🐞 bug

#272 fix: do not set auth-token-user, if username is given
  docs/Configuration.md
  go.mod
  go.sum
  internal/config/flags.go
  internal/oauth2/handler_test.go
  internal/openvpn/callbacks.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/state/state.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: 🐞 bug

#275 Add CI for spell
  .github/workflows/spelling.yaml
  docs/Home.md
  docs/Providers.md
  internal/openvpn/main.go
  internal/state/state_test.go
Labels: chore
