Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-12, with the labels that each got.

#362 Clarify docs
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/question.yaml
  docs/Configuration.md
  docs/FAQ.md
  docs/Layout Customization.md
  internal/config/flags.go
  internal/config/flags_test.go
  internal/config/validate.go
Labels: 📖 docs

#365 Fix demo issues by updating Go to 1.23 and removing an unsupported OpenVPN client directive.
  docs/demo/docker-compose.yaml
Labels: 📖 docs

#373 update dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#377 Stricter lint rules
  .golangci.yaml
  cmd/daemon/root.go
  docs/Non-interactive session refresh.md
  go.mod
  go.sum
  go.work.sum
  internal/config/defaults.go
  internal/config/url.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/providers/github/api.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/providers/github/check_test.go
  internal/oauth2/providers/github/user_test.go
  internal/oauth2/providers/google/check.go
  internal/oauth2/providers/google/check_test.go
  internal/openvpn/errors.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/storage/storage.go
  internal/utils/overlayfs.go
  internal/utils/testutils/main.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#381 small lint fixes
  cmd/daemon/root.go
  cmd/daemon/root_test.go
Labels: chore
