Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-02, with the labels that each got.

#133 Fix connections from IPv6 clients
  internal/openvpn/connection/client.go
  pkg/plugin/client.go
Labels: bug

#147 docs: read sensitive data from files
  README.md
  cmd/daemon/root_test.go
  docs/Configuration.md
  go.work.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/load.go
  internal/httpserver/main_test.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/refresh_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/connection/client.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/state/state.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: docs

#151 BREAKING: openvpn.bypass.cn -> openvpn.bypass.common-names
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  docs/Configuration.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/load_test.go
  internal/config/types.go
Labels: breaking-change

#153 Switch to go 1.22
  go.mod
  go.sum
  go.work
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: dependencies

#156 If multiple groups are configured, the user needs to be least in one group instead of all groups.
  internal/config/config.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/check_test.go
Labels: breaking-change

#157 HTTP: restrict methods to GET
  internal/oauth2/handler.go
Labels: enhancement

#158 Implement acr verifier
  docs/Configuration.md
  internal/config/config.go
  internal/config/types.go
  internal/httpserver/main_test.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/refresh_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/main_test.go
  pkg/testutils/logger.go
  pkg/testutils/main.go
Labels: enhancement

#165 Update Providers.md
  docs/Providers.md
Labels: docs

#167 Update Providers.md with consent for preexisting Google app
  docs/Providers.md
Labels: docs

#169 Hardening builds and systemd unit file and setup system group
  .github/workflows/ci.yaml
  .gitignore
  .goreleaser.yaml
  docs/Configuration.md
  internal/config/secret.go
  internal/oauth2/handler.go
  packaging/config.yaml
  packaging/etc/openvpn-auth-oauth2/config.yaml
  packaging/etc/sysconfig/openvpn-auth-oauth2
  packaging/openvpn-auth-oauth2.service
  packaging/postinstall.sh
  packaging/preremove.sh
  packaging/scripts/postinst.sh
  packaging/scripts/postremove.sh
  packaging/scripts/preinst.sh
  packaging/scripts/preremove.sh
  packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
  packaging/usr/lib/sysusers.d/openvpn-auth-oauth2.conf
  tests/docker-compose.yaml
  tests/systemd/docker-compose.yaml
Labels: enhancement

#171 Add `openvpn.common-name.environment-variable-name`
  docs/Configuration.md
  internal/config/config.go
  internal/config/defaults.go
  internal/config/load_test.go
  internal/config/types.go
  internal/openvpn/client.go
  internal/openvpn/connection/bench_test.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/handler.go
  internal/openvpn/main_test.go
  packaging/etc/openvpn-auth-oauth2/config.yaml
Labels: enhancement

#176 Mention `auth-user-pass-optional`
  docs/Configuration.md
Labels: docs

#177 Disable syscall filter
  packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
Labels: bug

#178 Handle SIGHUP of OpenVPN server
  .github/workflows/ci.yaml
  cmd/daemon/root.go
  cmd/daemon/root_test.go
  go.mod
  go.sum
  go.work.sum
  internal/internal_test.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider_test.go
  internal/oauth2/refresh_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/types.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  pkg/testutils/main.go
Labels: bug

#179 Add more details docs to GCP Provider
  docs/Debugging Errors.md
Labels: docs

#180 Add option for management client passthrough
  .golangci.yaml
  .run/go test openvpn-auth-oauth2.run.xml
  Makefile
  cmd/daemon/root.go
  cmd/daemon/root_test.go
  docs/Configuration.md
  docs/Installation.md
  docs/Providers.md
  internal/config/config.go
  internal/config/defaults.go
  internal/config/load_test.go
  internal/config/types.go
  internal/internal_test.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/refresh.go
  internal/oauth2/providers/google/check.go
  internal/oauth2/refresh_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  internal/openvpn/types.go
  internal/utils/lookup.go
  internal/utils/lookup_test.go
  packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
  pkg/testutils/listener.go
  pkg/testutils/main.go
  tests/docker-compose.yaml
Labels: enhancement

#181 Add keycloak docs
  docs/Providers.md
Labels: docs

#182 Add a demo
  .editorconfig
  demo/.gitignore
  demo/README.md
  demo/docker-compose.yaml
  demo/keycloak-realm.json
  demo/openvpn-server.conf
  docs/Demo.md
  docs/Home.md
  tests/docker-compose.yaml
Labels: docs

#186 Use \r\n as new-line separator and ignore quit
  internal/openvpn/passthrough.go
Labels: bug

#187 Check common name in case sensitive mode by default
  docs/Configuration.md
  internal/config/config.go
  internal/config/load_test.go
  internal/config/types.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/check_test.go
Labels: breaking-change

#183 Make Token Endpoint AuthStyle configurable
  docs/Configuration.md
  docs/Installation.md
  go.mod
  go.sum
  go.work.sum
  internal/config/config.go
  internal/config/defaults.go
  internal/config/load_test.go
  internal/config/types.go
  internal/config/types_test.go
  internal/oauth2/provider.go
  internal/openvpn/bench_test.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  pkg/testutils/main.go
Labels: enhancement

#192 Fix deadlock on unknown messages
  internal/config/config.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/callbacks.go
  internal/openvpn/connection/bench_test.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  internal/state/state.go
  pkg/testutils/main.go
Labels: bug

#189 Support Session ID
  .golangci.yaml
  docs/Configuration.md
  docs/Debugging Errors.md
  docs/img/logo.png
  internal/config/config.go
  internal/config/types.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/refresh.go
  internal/oauth2/providers/github/refresh.go
  internal/oauth2/providers/google/refresh.go
  internal/oauth2/refresh.go
  internal/oauth2/refresh_test.go
  internal/oauth2/types.go
  internal/openvpn/callbacks.go
  internal/openvpn/client.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/handler.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough_test.go
  internal/state/bench_test.go
  internal/state/state.go
  internal/state/state_test.go
  internal/storage/storage.go
  internal/storage/storage_test.go
  internal/ui/static/favicon.png
  packaging/etc/openvpn-auth-oauth2/config.yaml
  pkg/testutils/main.go
  tests/docker-compose.yaml
Labels: enhancement

#194 Reload TLS certificate on SIGHUP
  .codecov.yml
  cmd/daemon/root.go
  cmd/daemon/root_test.go
  docs/Configuration.md
  internal/httpserver/main.go
  internal/httpserver/main_test.go
  pkg/plugin/main.go
  pkg/testutils/main.go
  tests/docker-compose.yaml
Labels: enhancement

#196 BREAKING: Use Google Cloud Identity API for check Google Group memberships. Check docs.
  .github/workflows/pr-check.yaml
  .golangci.yaml
  cmd/daemon/root.go
  docs/Configuration.md
  docs/Providers.md
  go.mod
  go.sum
  go.work.sum
  internal/config/config.go
  internal/config/defaults.go
  internal/config/load_test.go
  internal/config/types.go
  internal/oauth2/handler.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/refresh.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/providers/github/refresh.go
  internal/oauth2/providers/github/user.go
  internal/oauth2/providers/google/api.go
  internal/oauth2/providers/google/check.go
  internal/oauth2/providers/google/check_test.go
  internal/oauth2/providers/google/config.go
  internal/oauth2/providers/google/credentials.go
  internal/oauth2/providers/google/main.go
  internal/oauth2/providers/google/refresh.go
  internal/oauth2/refresh.go
  internal/oauth2/refresh_test.go
  internal/oauth2/types.go
  internal/oauth2/types/token.go
  internal/oauth2/types/userdata.go
  internal/openvpn/bench_test.go
  internal/openvpn/client.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough_test.go
  packaging/etc/openvpn-auth-oauth2/config.yaml
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  pkg/plugin/plugin.go
  pkg/testutils/http.go
  pkg/testutils/main.go
Labels: 💥 breaking-change

#197 Increase test coverage
  internal/oauth2/handler_test.go
  internal/oauth2/providers/github/api.go
  internal/oauth2/providers/github/check.go
  internal/oauth2/providers/github/check_test.go
  internal/oauth2/providers/github/user.go
  internal/oauth2/providers/github/user_test.go
  internal/oauth2/providers/google/api.go
  internal/oauth2/providers/google/check_test.go
  internal/openvpn/passthrough_test.go
  pkg/testutils/http.go
  pkg/testutils/main.go
Labels: chore

#199 Log client IP
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/check.go
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/refresh.go
  internal/openvpn/client.go
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/main_test.go
  internal/state/bench_test.go
  internal/state/state.go
  internal/state/state_test.go
  pkg/plugin/client.go
  pkg/plugin/plugin.go
  tests/docker-compose.yaml
Labels: ✨ enhancement

#200 Log client IP
  internal/openvpn/connection/client.go
  internal/openvpn/connection/client_test.go
Labels: chore

#204 Add --log.vpn-client-ip
  docs/Configuration.md
  internal/config/config.go
  internal/config/defaults.go
  internal/config/load_test.go
  internal/config/types.go
  internal/openvpn/client.go
  packaging/etc/openvpn-auth-oauth2/config.yaml
Labels: ✨ enhancement
