Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-11, with the labels that each got.

#339 deps: update all dependencies
  go.mod
  go.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#342 chore: enable sloglint
  .golangci.yaml
  internal/httpserver/main.go
  internal/oauth2/handler.go
  internal/oauth2/provider.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/refresh.go
  internal/openvpn/main_test.go
Labels: chore

#345 chore(deps): bump dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#343 fix: trim newlines from files reading by secrets
  internal/config/secret.go
Labels: 🐞 bug

#349 fix: do not store refresh token, if empty.
  internal/oauth2/refresh.go
  internal/oauth2/refresh_test.go
Labels: 🐞 bug

#350 chore(deps): bump dependencies
  .github/workflows/ci.yaml
  .golangci.yaml
  cmd/daemon/full_test.go
  cmd/daemon/root_test.go
  go.mod
  go.sum
  internal/oauth2/refresh_test.go
  internal/utils/testutils/logger.go
  pkg/plugin/go.mod
  pkg/plugin/go.sum
  tools/go.mod
  tools/go.sum
Labels: 🛠️ dependencies

#355 Add armenian language
  internal/ui/assets/i18n/hy.json
Labels: ✨ enhancement
