Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2024-03, with the labels that each got.

#206 Added nil check to Check functions
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/providers/generic/user.go
  internal/oauth2/providers/github/user_test.go
Labels: 🐞 bug

#209 update deps
  go.mod
  go.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: 🛠️ dependencies

#212 makefile: force LF on checkout
  .gitattributes
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: 🐞 bug

#213 add 3rdpartylicenses
  .github/workflows/ci.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
Labels: 📖 docs

#214 add 3rdpartylicenses with goreleaser
  .github/workflows/ci.yaml
  .goreleaser.yaml
Labels: chore

#215 increase test coverage
  .golangci.yaml
  cmd/daemon/root.go
  cmd/daemon/root_test.go
  internal/config/flags.go
  internal/config/flags_test.go
  internal/config/validate.go
  internal/httpserver/main.go
  internal/httpserver/main_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/main.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  pkg/plugin/plugin.go
  pkg/testutils/main.go
Labels: chore

#216 increase test coverage
  .gitignore
  cmd/daemon/root.go
  internal/httpserver/main.go
  internal/httpserver/main_test.go
  internal/internal_test.go
  internal/oauth2/handler_test.go
  internal/oauth2/refresh_test.go
  internal/openvpn/main.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  pkg/plugin/plugin.go
  pkg/testutils/main.go
Labels: chore

#221 log id token claims on debug level
  .github/workflows/ci.yaml
  Makefile
  cmd/daemon/root_test.go
  internal/config/decode_hooks_test.go
  internal/config/flags_test.go
  internal/config/load_test.go
  internal/config/url_test.go
  internal/httpserver/main_test.go
  internal/internal_test.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider_test.go
  internal/oauth2/providers/generic/check_test.go
  internal/oauth2/providers/github/check_test.go
  internal/oauth2/providers/github/user_test.go
  internal/oauth2/providers/google/check_test.go
  internal/oauth2/refresh_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/connection/bench_test.go
  internal/openvpn/connection/client_test.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough_test.go
  internal/state/bench_test.go
  internal/utils/common_name_test.go
  internal/utils/lookup_test.go
  pkg/testutils/main.go
Labels: ✨ enhancement

#222 bump dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/plugin/go.mod
  pkg/plugin/go.sum
Labels: 🛠️ dependencies

#223 passthrough: Add welcome message
  internal/openvpn/bench_test.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  internal/openvpn/types.go
Labels: 🐞 bug

#224 Provide BSD builds
  .goreleaser.yaml
Labels: ✨ enhancement

#225 passthrough: fix status 2+3 commands
  .github/workflows/ci.yaml
  Makefile
  internal/openvpn/bench_test.go
  internal/openvpn/handler.go
  internal/openvpn/passthrough.go
  internal/openvpn/passthrough_test.go
  renovate.json
Labels: 🐞 bug

#227 openvpn: fix hang on invalid password
  .gitignore
  cmd/daemon/root.go
  internal/oauth2/providers/google/api.go
  internal/oauth2/providers/google/config.go
  internal/openvpn/handler.go
  tests/Dockerfile
  tests/docker-compose.yaml
  tests/systemd/docker-compose.yaml
Labels: 🐞 bug

#230 systemd: Enable hardenings
  .goreleaser.yaml
  packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
  packaging/scripts/postinst.sh
  packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
  tests/systemd/Dockerfile
  tests/systemd/docker-compose.yaml
Labels: ✨ enhancement

#231 Do not use postinst script as preinst script
  .goreleaser.yaml
  packaging/scripts/postinst.sh
  packaging/scripts/postremove.sh
  packaging/scripts/preremove.sh
Labels: 🐞 bug

#232 Fix read files in etc dir
  packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
  packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
Labels: 🐞 bug

#233 DEB/RPM: Do not remove system group on upgrade
  .editorconfig
  packaging/scripts/postinst.sh
  packaging/scripts/postremove.sh
  packaging/scripts/preremove.sh
Labels: 🐞 bug

#234 Create nl.json
  internal/ui/assets/i18n/nl.json
Labels: ✨ enhancement

#235 Remove command whitelist
  .run/go test openvpn-auth-oauth2.run.xml
  internal/openvpn/connection/client.go
  internal/openvpn/handler.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough_test.go
Labels: chore

#238 nit: add context to storage class
  cmd/daemon/root.go
  cmd/state/root.go
  internal/oauth2/handler.go
  internal/oauth2/handler_test.go
  internal/oauth2/provider.go
  internal/oauth2/provider_test.go
  internal/openvpn/bench_test.go
  internal/openvpn/client.go
  internal/openvpn/main_test.go
  internal/openvpn/passthrough_test.go
  internal/state/bench_test.go
  internal/state/state.go
  internal/state/state_test.go
  internal/storage/storage.go
  internal/storage/storage_test.go
  pkg/plugin/plugin.go
  pkg/testutils/main.go
Labels: chore
