Repository jkroepke/openvpn-auth-oauth2, pull requests merged in 2025-08, with the labels that each got.

#580 chore(ci): remove pinentry
  .github/scripts/pinentry.sh
  .github/workflows/ci.yaml
  README.md
  docs/Article - How OIDC SSO Authentication works with OpenVPN Community Server.md
  docs/demo/docker-compose.yaml
  internal/oauth2/types/errors.go
Labels: chore

#581 feat: added supply-chain attestation
  .github/workflows/ci.yaml
  .goreleaser.yaml
Labels: ✨ enhancement

#587 docs: Remove AI scaffold text from Non-interactive session refresh.md
  docs/Non-interactive session refresh.md
Labels: 📖 docs

#588 feat: update to go 1.25
  DEVELOPER.md
  go.mod
Labels: ✨ enhancement

#590 feat: add refresh-nonce parameter to control nonce behavior on refresh
  docs/Configuration.md
  docs/Non-interactive session refresh.md
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/config/types_test.go
  internal/oauth2/providers/generic/oidc.go
  internal/oauth2/types/errors.go
  internal/utils/testutils/main.go
  packaging/etc/openvpn-auth-oauth2/config.yaml
  tests/docker-compose.yaml
Labels: ✨ enhancement
